name: TheChaatBar
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_timer_countdown: ^1.0.7
  permission_handler: ^11.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  provider: ^5.0.0
  shared_preferences: ^2.2.3
  google_fonts: ^4.0.3
  json_annotation: ^4.5.0
  toastification: ^2.0.0
  email_validator: ^2.1.16
  shimmer: ^2.0.0
  path_provider: ^2.0.11
  path: ^1.8.2
  image: ^4.0.15
  screenshot: ^3.0.0
  flutter_image_compress: ^1.1.0
  local_auth: ^2.2.0
  carousel_slider: ^4.2.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^17.2.1
  share_plus: ^10.0.0
  connectivity_plus: ^6.0.3
  smooth_page_indicator: ^1.1.0
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  flutter_keyboard_visibility: ^6.0.0
  sqflite: ^2.3.3+1
  floor: ^1.5.0
  device_info_plus: ^10.1.1
  flutter_broadcasts: ^0.4.0
  fluttertoast: ^8.2.1
  google_sign_in: 6.2.1
  curved_navigation_bar: ^1.0.6
  flutter_dash: ^1.0.0
  flutter_svg: ^2.0.0
  flutter_credit_card: ^4.0.1
  bottom_navy_bar: ^6.0.0
  animate_do: ^3.3.4
  gif: ^2.3.0
  cached_network_image: ^3.2.0
  otp_pin_field: ^1.3.2
  url_launcher: ^6.3.1
  sign_in_with_apple: ^6.1.4
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: CustomFont
      fonts:
        - asset: font/marlin_regular.otf
